/**
 * config/knowledgeBase.js
 * Central data store for the Kenya Crop Disease Expert System.
 */

const KNOWLEDGE_BASE = {
  maize: {
    label: "Maize",
    swahili: "Mahindi",
    varieties: [
      { id: "H614D", label: "H614D", notes: "Popular open-pollinated variety" },
      { id: "H6213", label: "H6213", notes: "High-yielding hybrid" },
      { id: "DK8031", label: "DK8031 (Dekalb)", notes: "Drought-tolerant hybrid" },
      { id: "SC403", label: "SC403 (Seedco)", notes: "Mid-altitude hybrid" },
      { id: "WEMA", label: "WEMA drought-tolerant", notes: "MLN-resistant, drought-tolerant" },
      { id: "Duma43", label: "Duma 43", notes: "Early maturing, MLN-tolerant" },
      { id: "PAN4M19", label: "PAN 4M-19", notes: "Commercial hybrid" },
      { id: "CSCS_BL8", label: "CSCS BL8", notes: "Short-season variety" },
    ],
    symptoms: {
      "yellow-streaks-leaves": { label: "Yellow streaks on leaves", swahili: "Mistari ya manjano kwenye majani" },
      "stunted-growth": { label: "Stunted / slow growth", swahili: "Ukuaji mdogo / polepole" },
      "dead-heart": { label: "Dead heart (central shoot dies)", swahili: "Moyo uliokufa (shina la kati linakufa)" },
      "premature-tasseling": { label: "Premature or abnormal tasseling", swahili: "Maua ya mapema au yasio ya kawaida" },
      "ear-rot": { label: "Ear/cob rot", swahili: "Kuoza kwa gunzi" },
      "rectangular-leaf-lesions": { label: "Rectangular lesions on leaves", swahili: "Vidonda vya mstatili kwenye majani" },
      "gray-tan-spots": { label: "Gray or tan spots on leaves", swahili: "Madoa ya kijivu au ya kahawia kwenye majani" },
      "lesions-parallel-veins": { label: "Lesions running parallel to leaf veins", swahili: "Vidonda vinavyoendana na mishipa ya majani" },
      "premature-leaf-death": { label: "Premature leaf death / drying", swahili: "Majani kukauka mapema" },
      "long-cigar-lesions": { label: "Long cigar-shaped lesions", swahili: "Vidonda virefu kama sigara" },
      "lesions-lower-leaves": { label: "Lesions starting on lower leaves first", swahili: "Vidonda vinaanza kwenye majani ya chini" },
      "narrow-yellow-streaks": { label: "Narrow chlorotic (yellow) streaks", swahili: "Mistari nyembamba ya njano" },
      "reduced-yield": { label: "Significantly reduced yield", swahili: "Mazao machache sana" },
      "stalk-discoloration": { label: "Stalk discoloration (brown inside)", swahili: "Shina kubadilika rangi (kahawia ndani)" },
      "lodging": { label: "Plant lodging / falling over", swahili: "Mimea kuanguka" },
      "pink-stalk-interior": { label: "Pink/red discoloration inside stalk", swahili: "Rangi ya waridi/nyekundu ndani ya shina" },
      "premature-death": { label: "Premature plant death", swahili: "Mmea kufa mapema" },
    },
    diseases: {
      "Maize Lethal Necrosis (MLN)": {
        clpRule: "maize-lethal-necrosis",
        requiredSymptoms: ["yellow-streaks-leaves", "stunted-growth"],
        confirmatorySymptoms: ["dead-heart", "ear-rot", "premature-tasseling"],
        weatherRisk: ["rainy"],
        baseConfidence: 90,
        treatment: "Remove and destroy infected plants immediately. Apply Cypermethrin to control aphid and thrip vectors. Do not replant maize for at least one season. Use MLN-resistant varieties.",
        prevention: "Use certified MLN-resistant seeds (WEMA, DK8031). Control aphids and thrips. Avoid planting near infected fields. Practice crop rotation.",
      },
      "Gray Leaf Spot": {
        clpRule: "maize-gray-leaf-spot",
        requiredSymptoms: ["rectangular-leaf-lesions", "gray-tan-spots"],
        confirmatorySymptoms: ["lesions-parallel-veins", "premature-leaf-death"],
        weatherRisk: ["humid", "rainy"],
        baseConfidence: 85,
        treatment: "Apply Mancozeb 80WP (2.5kg/ha) or Propiconazole (0.5L/ha). Remove and burn infected residues after harvest.",
        prevention: "Use resistant hybrids. Practice crop rotation with legumes. Avoid overhead irrigation. Plow crop residues.",
      },
      "Northern Leaf Blight": {
        clpRule: "maize-northern-leaf-blight",
        requiredSymptoms: ["long-cigar-lesions", "lesions-lower-leaves"],
        confirmatorySymptoms: ["premature-leaf-death"],
        weatherRisk: ["rainy", "cool"],
        baseConfidence: 80,
        treatment: "Apply Mancozeb 80WP or Chlorothalonil at disease onset. Ensure proper plant spacing for airflow.",
        prevention: "Plant resistant varieties. Rotate crops. Plow maize residues after harvest.",
      },
      "Maize Streak Virus": {
        clpRule: "maize-streak-virus",
        requiredSymptoms: ["yellow-streaks-leaves", "narrow-yellow-streaks"],
        confirmatorySymptoms: ["stunted-growth", "reduced-yield"],
        weatherRisk: ["dry", "warm"],
        baseConfidence: 88,
        treatment: "No chemical cure. Remove infected plants. Control leafhopper vectors with Imidacloprid 70WS.",
        prevention: "Use MSV-resistant varieties. Early planting. Monitor and control leafhoppers.",
      },
      "Fusarium Stalk Rot": {
        clpRule: "maize-stalk-rot",
        requiredSymptoms: ["stalk-discoloration", "lodging"],
        confirmatorySymptoms: ["pink-stalk-interior", "premature-death"],
        weatherRisk: ["rainy"],
        baseConfidence: 78,
        treatment: "No in-season cure. Harvest early. Ensure balanced fertilization (avoid excess nitrogen). Improve drainage.",
        prevention: "Use resistant varieties. Avoid high plant populations. Balanced soil nutrition. Improve drainage.",
      },
    },
  },

  tomato: {
    label: "Tomato",
    swahili: "Nyanya",
    varieties: [
      { id: "Rambo_F1", label: "Rambo F1", notes: "High-yielding, disease-tolerant" },
      { id: "Anna_F1", label: "Anna F1", notes: "TYLCV-resistant" },
      { id: "Tylka_F1", label: "Tylka F1", notes: "TYLCV-resistant, high yield" },
      { id: "MoneyMaker", label: "Money Maker", notes: "Popular open-pollinated variety" },
      { id: "Kilele_F1", label: "Kilele F1", notes: "Fusarium-tolerant" },
      { id: "Shanty_F1", label: "Shanty F1", notes: "Good shelf life" },
      { id: "RioGrande", label: "Rio Grande", notes: "Processing tomato variety" },
      { id: "CalJ", label: "Cal-J", notes: "Determinate, processing type" },
    ],
    symptoms: {
      "brown-spots-concentric-rings": { label: "Brown spots with concentric rings (target)", swahili: "Madoa ya kahawia yenye miduara" },
      "yellowing-around-spots": { label: "Yellowing around the spots", swahili: "Manjano karibu na madoa" },
      "lower-leaf-affected-first": { label: "Lower/older leaves affected first", swahili: "Majani ya chini yanaathiriwa kwanza" },
      "defoliation": { label: "Leaf drop / defoliation", swahili: "Majani kuanguka" },
      "water-soaked-lesions": { label: "Water-soaked lesions on leaves", swahili: "Vidonda vya maji kwenye majani" },
      "white-mold-leaf-underside": { label: "White mold on underside of leaves", swahili: "Ukungu mweupe chini ya majani" },
      "fruit-brown-rot": { label: "Brown rot on fruits", swahili: "Kuoza kwa kahawia kwenye matunda" },
      "rapid-plant-collapse": { label: "Rapid plant collapse", swahili: "Mmea kufa haraka" },
      "sudden-wilting": { label: "Sudden wilting (no prior yellowing)", swahili: "Kunyauka ghafla bila manjano" },
      "milky-bacterial-ooze": { label: "Milky ooze from cut stem in water", swahili: "Maji ya maziwa kutoka shina lililokatwa" },
      "brown-vascular-stem": { label: "Brown discoloration inside stem", swahili: "Kahawia ndani ya shina" },
      "yellow-curled-leaves": { label: "Yellow, curled/cupped leaves", swahili: "Majani ya njano yaliyokunjwa" },
      "flower-drop": { label: "Flower drop", swahili: "Maua kuanguka" },
      "small-fruit": { label: "Small or no fruit setting", swahili: "Matunda madogo au kutotokea" },
      "yellowing-one-side": { label: "Yellowing on one side of plant", swahili: "Manjano upande mmoja wa mmea" },
      "wilting-lower-leaves": { label: "Wilting of lower leaves first", swahili: "Majani ya chini kunyauka kwanza" },
    },
    diseases: {
      "Early Blight (Alternaria)": {
        clpRule: "tomato-early-blight",
        requiredSymptoms: ["brown-spots-concentric-rings", "lower-leaf-affected-first"],
        confirmatorySymptoms: ["yellowing-around-spots", "defoliation"],
        weatherRisk: ["rainy", "humid"],
        baseConfidence: 88,
        treatment: "Apply Mancozeb 80WP or Copper Oxychloride every 7-10 days. Remove infected lower leaves.",
        prevention: "Avoid overhead irrigation. Mulch to reduce soil splash. Use certified seeds.",
      },
      "Late Blight (Phytophthora)": {
        clpRule: "tomato-late-blight",
        requiredSymptoms: ["water-soaked-lesions", "white-mold-leaf-underside"],
        confirmatorySymptoms: ["fruit-brown-rot", "rapid-plant-collapse"],
        weatherRisk: ["rainy", "cool"],
        baseConfidence: 93,
        treatment: "Apply Ridomil Gold MZ urgently (2.5kg/ha). Remove and burn infected plants.",
        prevention: "Plant resistant varieties. Avoid waterlogging. Spray preventively at rainy season onset.",
      },
      "Bacterial Wilt": {
        clpRule: "tomato-bacterial-wilt",
        requiredSymptoms: ["sudden-wilting", "milky-bacterial-ooze"],
        confirmatorySymptoms: ["brown-vascular-stem"],
        weatherRisk: ["rainy", "warm"],
        baseConfidence: 94,
        treatment: "No cure. Remove all infected plants. Disinfect tools with 10% bleach. 3+ year rotation.",
        prevention: "Resistant varieties. 3-year rotation. Improve drainage. Certified planting material.",
      },
      "Tomato Yellow Leaf Curl Virus (TYLCV)": {
        clpRule: "tomato-tylcv",
        requiredSymptoms: ["yellow-curled-leaves", "flower-drop"],
        confirmatorySymptoms: ["small-fruit", "stunted-growth"],
        weatherRisk: ["dry", "warm"],
        baseConfidence: 92,
        treatment: "Remove infected plants. Control whitefly with Imidacloprid or Acetamiprid.",
        prevention: "Use TYLCV-resistant varieties (Tylka F1, Anna F1). Insect-proof nets. Monitor whiteflies.",
      },
      "Fusarium Wilt": {
        clpRule: "tomato-fusarium-wilt",
        requiredSymptoms: ["yellowing-one-side", "wilting-lower-leaves"],
        confirmatorySymptoms: ["brown-vascular-stem", "stunted-growth"],
        weatherRisk: ["warm"],
        baseConfidence: 85,
        treatment: "No cure. Remove infected plants. Apply Trichoderma to remaining plants. Soil solarization.",
        prevention: "Resistant/tolerant varieties (Kilele F1). Soil solarization. Crop rotation.",
      },
    },
  },

  potato: {
    label: "Potato",
    swahili: "Viazi",
    varieties: [
      { id: "Shangi", label: "Shangi", notes: "Most popular Kenyan variety" },
      { id: "Tigoni", label: "Tigoni", notes: "KALRO bred, late blight resistant" },
      { id: "DutchRobijn", label: "Dutch Robijn", notes: "High yield, susceptible to blight" },
      { id: "KenyaMpya", label: "Kenya Mpya", notes: "KALRO bred, early maturing" },
      { id: "Asante", label: "Asante", notes: "Late blight tolerant" },
      { id: "Unica", label: "Unica", notes: "Dual-purpose processing variety" },
      { id: "Sherekea", label: "Sherekea", notes: "Late blight resistant" },
      { id: "Nyota", label: "Nyota", notes: "KALRO variety, highland adapted" },
    ],
    symptoms: {
      "water-soaked-leaf-spots": { label: "Water-soaked spots on leaves", swahili: "Madoa ya maji kwenye majani" },
      "white-sporulation-underside": { label: "White/gray sporulation on leaf underside", swahili: "Ukungu mweupe chini ya majani" },
      "tuber-rot": { label: "Tuber rot (brown/black)", swahili: "Viazi kuoza (kahawia/nyeusi)" },
      "rapid-foliage-death": { label: "Rapid browning and death of foliage", swahili: "Majani kufa haraka na kuwa kahawia" },
      "wilting-upper-leaves": { label: "Wilting starting from upper leaves", swahili: "Kunyauka kuanzia majani ya juu" },
      "yellowing-margins": { label: "Yellowing at leaf margins", swahili: "Njano kwenye ukingo wa majani" },
      "brown-ring-tuber": { label: "Brown ring visible when tuber is cut", swahili: "Pete ya kahawia inaonekana kiazi kikikatwa" },
      "milky-ooze-stem": { label: "Milky/slimy ooze from cut stem", swahili: "Majimaji mazito kutoka shina lililokatwa" },
      "rough-scabby-tuber-skin": { label: "Rough, scabby tuber skin", swahili: "Ngozi ya kiazi yenye ukakasi" },
      "shallow-pits-tuber": { label: "Shallow pits on tuber surface", swahili: "Mashimo madogo kwenye uso wa kiazi" },
      "corky-lesions-tuber": { label: "Corky or warty lesions on tuber", swahili: "Vidonda vya korki kwenye kiazi" },
      "mosaic-mottling": { label: "Mosaic / mottling pattern on leaves", swahili: "Mfumo wa mosaic kwenye majani" },
      "necrotic-spots-leaves": { label: "Necrotic (dead) spots on leaves", swahili: "Madoa ya kufa kwenye majani" },
      "leaf-drop": { label: "Leaf drop", swahili: "Majani kuanguka" },
    },
    diseases: {
      "Late Blight (Phytophthora infestans)": {
        clpRule: "potato-late-blight",
        requiredSymptoms: ["water-soaked-leaf-spots", "white-sporulation-underside"],
        confirmatorySymptoms: ["tuber-rot", "rapid-foliage-death"],
        weatherRisk: ["rainy", "cool"],
        baseConfidence: 95,
        treatment: "Apply Ridomil Gold MZ 68WP (2.5kg/ha) immediately. Spray every 7-10 days. Remove infected haulms before harvest.",
        prevention: "Certified disease-free seed tubers. Resistant varieties (Asante, Sherekea). Preventive copper sprays.",
      },
      "Bacterial Wilt": {
        clpRule: "potato-bacterial-wilt",
        requiredSymptoms: ["wilting-upper-leaves", "brown-ring-tuber"],
        confirmatorySymptoms: ["milky-ooze-stem", "yellowing-margins"],
        weatherRisk: ["warm", "rainy"],
        baseConfidence: 93,
        treatment: "No cure. Remove and destroy all infected plants and tubers. Disinfect tools with bleach.",
        prevention: "Certified seed tubers. 3-year rotation. Improve drainage. Avoid previously infected fields.",
      },
      "Common Scab": {
        clpRule: "potato-common-scab",
        requiredSymptoms: ["rough-scabby-tuber-skin", "shallow-pits-tuber"],
        confirmatorySymptoms: ["corky-lesions-tuber"],
        weatherRisk: ["dry"],
        baseConfidence: 80,
        treatment: "No in-season cure. Tubers still edible after peeling. Adjust soil pH below 5.2. Uniform irrigation.",
        prevention: "Certified seed. Maintain soil pH 5.0-5.2. Consistent moisture during tuber initiation.",
      },
      "Potato Virus Y (PVY)": {
        clpRule: "potato-virus-y",
        requiredSymptoms: ["mosaic-mottling", "necrotic-spots-leaves"],
        confirmatorySymptoms: ["stunted-growth", "leaf-drop"],
        weatherRisk: ["dry", "warm"],
        baseConfidence: 82,
        treatment: "Remove infected plants. Control aphid vectors with Imidacloprid.",
        prevention: "Certified virus-free seed. Control aphids. Remove volunteer potato plants.",
      },
    },
  },

  coffee: {
    label: "Coffee",
    swahili: "Kahawa",
    varieties: [
      { id: "Ruiru11", label: "Ruiru 11", notes: "CBD & CLR resistant, KALRO bred" },
      { id: "Batian", label: "Batian", notes: "Multi-disease resistant, high quality" },
      { id: "SL28", label: "SL28", notes: "High quality, disease-susceptible" },
      { id: "SL34", label: "SL34", notes: "Highland adapted, susceptible to rust" },
      { id: "K7", label: "K7", notes: "Older variety, moderate resistance" },
      { id: "BlueMountain", label: "Blue Mountain", notes: "Specialty grade variety" },
    ],
    symptoms: {
      "orange-yellow-pustules-underside": { label: "Orange/yellow pustules on leaf underside", swahili: "Vipele vya rangi ya chungwa chini ya majani" },
      "yellow-spots-upper-leaf": { label: "Yellow spots on upper leaf surface", swahili: "Madoa ya njano juu ya majani" },
      "defoliation": { label: "Defoliation / leaf drop", swahili: "Majani kuanguka" },
      "reduced-berry-set": { label: "Reduced or no berry setting", swahili: "Matunda machache au kutotokea" },
      "dark-sunken-berry-lesions": { label: "Dark sunken lesions on berries", swahili: "Vidonda vya giza vilivyozama kwenye matunda" },
      "premature-berry-drop": { label: "Premature berry drop", swahili: "Matunda kuanguka mapema" },
      "mummified-berries": { label: "Mummified / shriveled berries", swahili: "Matunda yaliyokauka na kusalia mkononi" },
      "brown-bean-discoloration": { label: "Brown discoloration of coffee beans", swahili: "Kahawa kubadilika rangi ya kahawia" },
      "sudden-wilting-branches": { label: "Sudden wilting of branches", swahili: "Matawi kunyauka ghafla" },
      "brown-wood-inside": { label: "Brown/dark wood when branch cut", swahili: "Mbao ya kahawia ndani ya tawi lililokatwa" },
      "bark-peeling": { label: "Bark peeling or cracking", swahili: "Gome kuuma au kupasuka" },
      "tree-death": { label: "Complete tree death / dieback", swahili: "Mti kufa kabisa" },
    },
    diseases: {
      "Coffee Leaf Rust (CLR)": {
        clpRule: "coffee-leaf-rust",
        requiredSymptoms: ["orange-yellow-pustules-underside", "yellow-spots-upper-leaf"],
        confirmatorySymptoms: ["defoliation", "reduced-berry-set"],
        weatherRisk: ["rainy", "humid"],
        baseConfidence: 95,
        treatment: "Apply Copper Oxychloride 50WP (3kg/100L) or Bayleton (Triadimefon). Spray every 3 weeks in rainy season.",
        prevention: "Use resistant varieties (Ruiru 11, Batian). Regular pruning. Preventive copper sprays at onset of rains.",
      },
      "Coffee Berry Disease (CBD)": {
        clpRule: "coffee-berry-disease",
        requiredSymptoms: ["dark-sunken-berry-lesions", "premature-berry-drop"],
        confirmatorySymptoms: ["mummified-berries", "brown-bean-discoloration"],
        weatherRisk: ["rainy"],
        baseConfidence: 94,
        treatment: "Apply Copper Oxychloride or Benomyl at berry formation. Remove and destroy all infected berries.",
        prevention: "CBD-resistant varieties (Ruiru 11, Batian). Time sprays with berry development. Remove mummified berries.",
      },
      "Coffee Wilt Disease": {
        clpRule: "coffee-wilt",
        requiredSymptoms: ["sudden-wilting-branches", "brown-wood-inside"],
        confirmatorySymptoms: ["bark-peeling", "tree-death"],
        weatherRisk: ["rainy", "warm"],
        baseConfidence: 88,
        treatment: "No cure. Remove and burn infected trees. Disinfect all cutting tools with 70% alcohol.",
        prevention: "Certified planting material. Disinfect tools. Avoid soil disturbance near roots. Quarantine infected areas.",
      },
    },
  },

  banana: {
    label: "Banana",
    swahili: "Ndizi",
    varieties: [
      { id: "Williams", label: "Williams", notes: "Cavendish type, most common" },
      { id: "GiantCavendish", label: "Giant Cavendish", notes: "High yield, export grade" },
      { id: "Kisukari", label: "Kisukari", notes: "Sweet local variety (Muraru)" },
      { id: "GrossMichel", label: "Gros Michel", notes: "Traditional variety, wilt-susceptible" },
      { id: "FHIA01", label: "FHIA-01 (Goldfinger)", notes: "Disease-resistant hybrid" },
      { id: "FHIA17", label: "FHIA-17", notes: "Fusarium-resistant hybrid" },
      { id: "UgandaGreen", label: "Uganda Green (Matoke)", notes: "Cooking banana" },
    ],
    symptoms: {
      "yellow-wilting-leaves": { label: "Yellowing and wilting of leaves", swahili: "Majani kuwa njano na kunyauka" },
      "premature-fruit-ripening": { label: "Premature or uneven fruit ripening", swahili: "Matunda kuiva mapema au kwa njia isiyo sawa" },
      "yellow-ooze-cut-stem": { label: "Yellow ooze from cut pseudostem", swahili: "Majimaji ya njano kutoka shina lililokatwa" },
      "internal-fruit-discoloration": { label: "Brown/yellow discoloration inside fruit", swahili: "Rangi ya kahawia ndani ya tunda" },
      "yellowing-lower-leaves": { label: "Yellowing starting from lower/older leaves", swahili: "Njano kuanza kwenye majani ya chini" },
      "splitting-pseudostem": { label: "Splitting of pseudostem", swahili: "Shina kupasuka" },
      "brown-vascular-tissue": { label: "Brown vascular tissue in pseudostem", swahili: "Mishipa ya kahawia ndani ya shina" },
      "plant-collapse": { label: "Complete plant collapse", swahili: "Mmea kuanguka kabisa" },
      "dark-streaks-leaves": { label: "Dark brown/black streaks on leaves", swahili: "Mistari ya giza kwenye majani" },
      "black-leaf-spots": { label: "Black spots with yellow halo on leaves", swahili: "Madoa meusi yenye pete ya njano" },
      "rapid-leaf-death": { label: "Rapid leaf death (necrosis)", swahili: "Majani kufa haraka" },
      "reduced-bunch-weight": { label: "Reduced bunch size / weight", swahili: "Nguzo ndogo / nyepesi" },
    },
    diseases: {
      "Banana Bacterial Wilt (BBW)": {
        clpRule: "banana-bacterial-wilt",
        requiredSymptoms: ["yellow-wilting-leaves", "yellow-ooze-cut-stem"],
        confirmatorySymptoms: ["premature-fruit-ripening", "internal-fruit-discoloration"],
        weatherRisk: ["rainy", "warm"],
        baseConfidence: 96,
        treatment: "Remove and destroy entire infected mat (plant + all suckers). Chop and bury or burn. Disinfect tools with 10% bleach after each plant. Remove male flower buds on healthy plants.",
        prevention: "Disease-free suckers from certified sources. Disinfect cutting tools. Remove male bud after last hand sets.",
      },
      "Panama Disease (Fusarium Wilt)": {
        clpRule: "banana-fusarium-wilt",
        requiredSymptoms: ["yellowing-lower-leaves", "brown-vascular-tissue"],
        confirmatorySymptoms: ["splitting-pseudostem", "plant-collapse"],
        weatherRisk: ["warm"],
        baseConfidence: 91,
        treatment: "No cure. Remove and destroy infected mats. Avoid moving soil from infected areas. Long rotation (10+ years).",
        prevention: "Resistant varieties (FHIA-01, FHIA-17). Certified clean planting material. Avoid contaminated soil.",
      },
      "Black Sigatoka": {
        clpRule: "banana-black-sigatoka",
        requiredSymptoms: ["dark-streaks-leaves", "black-leaf-spots"],
        confirmatorySymptoms: ["rapid-leaf-death", "reduced-bunch-weight"],
        weatherRisk: ["rainy", "humid"],
        baseConfidence: 88,
        treatment: "Apply Mancozeb 80WP or Propiconazole. Remove and destroy infected leaves. Regular deleafing.",
        prevention: "Resistant varieties. Proper spacing (3m x 3m). Regular deleafing of 3-4 oldest leaves.",
      },
    },
  },

  beans: {
    label: "Beans",
    swahili: "Maharagwe",
    varieties: [
      { id: "Katumani", label: "Katumani", notes: "Drought-tolerant, semi-arid" },
      { id: "Lyamungu85", label: "Lyamungu 85", notes: "Rust-resistant" },
      { id: "Jesca", label: "Jesca", notes: "High yield, rust-tolerant" },
      { id: "Mwitemania", label: "Mwitemania", notes: "BCMV-resistant" },
      { id: "Selian97", label: "Selian 97", notes: "BCMV-resistant, high yield" },
      { id: "MieziMiwili", label: "Miezi Miwili", notes: "Fast-maturing, 60 days" },
      { id: "KALRORosecoco", label: "KALRO Rosecoco", notes: "KALRO improved variety" },
      { id: "KK8", label: "KK8", notes: "Commercial variety" },
    ],
    symptoms: {
      "orange-brown-pustules": { label: "Orange/brown pustules on leaves", swahili: "Vipele vya rangi ya chungwa/kahawia kwenye majani" },
      "yellowing-around-pustules": { label: "Yellowing surrounding pustules", swahili: "Manjano karibu na vipele" },
      "defoliation": { label: "Leaf drop / defoliation", swahili: "Majani kuanguka" },
      "premature-pod-drop": { label: "Premature pod drop", swahili: "Mikunde kuanguka mapema" },
      "angular-water-soaked-spots": { label: "Angular water-soaked spots on leaves", swahili: "Madoa ya pembe yenye maji kwenye majani" },
      "gray-brown-leaf-lesions": { label: "Gray/brown angular lesions on leaves", swahili: "Vidonda vya kijivu/kahawia kwenye majani" },
      "pod-lesions": { label: "Lesions / spots on pods", swahili: "Vidonda kwenye mikunde" },
      "seed-discoloration": { label: "Seed discoloration or shriveling", swahili: "Mbegu kubadilika rangi au kukauka" },
      "mosaic-mottling": { label: "Mosaic / mottling on leaves", swahili: "Mfumo wa mosaic kwenye majani" },
      "leaf-malformation": { label: "Leaf malformation / distortion", swahili: "Majani kupinda au kupotoka umbo" },
      "stunted-growth": { label: "Stunted growth", swahili: "Ukuaji mdogo" },
      "reduced-pod-set": { label: "Reduced or no pod setting", swahili: "Mikunde michache au kutotokea" },
    },
    diseases: {
      "Bean Rust": {
        clpRule: "beans-rust",
        requiredSymptoms: ["orange-brown-pustules", "yellowing-around-pustules"],
        confirmatorySymptoms: ["defoliation", "premature-pod-drop"],
        weatherRisk: ["rainy", "cool"],
        baseConfidence: 88,
        treatment: "Apply Mancozeb 80WP or Copper Oxychloride every 10-14 days. Remove heavily infected plants.",
        prevention: "Rust-resistant varieties (Jesca, Lyamungu 85). Avoid dense planting. Crop rotation.",
      },
      "Angular Leaf Spot": {
        clpRule: "beans-angular-leaf-spot",
        requiredSymptoms: ["angular-water-soaked-spots", "gray-brown-leaf-lesions"],
        confirmatorySymptoms: ["pod-lesions", "seed-discoloration"],
        weatherRisk: ["rainy"],
        baseConfidence: 83,
        treatment: "Apply Copper Oxychloride 50WP (3kg/ha). Remove heavily infected plant debris.",
        prevention: "Certified disease-free seed. 2-year crop rotation. Avoid overhead irrigation.",
      },
      "Bean Common Mosaic Virus (BCMV)": {
        clpRule: "beans-mosaic-virus",
        requiredSymptoms: ["mosaic-mottling", "leaf-malformation"],
        confirmatorySymptoms: ["stunted-growth", "reduced-pod-set"],
        weatherRisk: ["dry", "warm"],
        baseConfidence: 85,
        treatment: "No chemical cure. Remove infected plants. Control aphid vectors with Imidacloprid.",
        prevention: "Certified virus-free seed. BCMV-resistant varieties (Mwitemania, Selian 97). Control aphids.",
      },
    },
  },
};

export default KNOWLEDGE_BASE;